# Generated by Django 6.0.6 on 2026-06-24 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام محصول/زیورآلات')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='اسلاگ (URL)')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='وزن (گرم)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات محصول')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر اصلی محصول')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در ویترین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categorys.productcategorymodel', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول ویترین',
                'verbose_name_plural': 'محصولات ویترین',
            },
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='تصویر گالری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productmodel', verbose_name='محصول مربوطه')),
            ],
            options={
                'verbose_name': 'تصویر گالری محصول',
                'verbose_name_plural': 'گالری تصاویر محصولات',
            },
        ),
    ]
