# Generated by Django 6.0.6 on 2026-07-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='other_costs',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='هزینه\u200cهای جانبی (ریال)'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='profit_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='سود (%)'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='مالیات (%)'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='wage_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='اجرت (%)'),
        ),
    ]
