# Generated by Django 6.0.6 on 2026-06-25 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customermodel_national_code'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGoalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نشان کردن')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='customers.customermodel', verbose_name='مشتری')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_by', to='products.productmodel', verbose_name='محصول هدف')),
            ],
            options={
                'verbose_name': 'هدف خرید مشتری',
                'verbose_name_plural': 'اهداف خرید مشتریان',
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
