# Generated by Django 6.0.6 on 2026-07-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت در سیستم')),
            ],
            options={
                'verbose_name': 'قیمت طلا',
                'verbose_name_plural': 'تاریخچه قیمت طلا',
                'ordering': ['-created_at'],
            },
        ),
    ]
