# Generated by Django 6.0.6 on 2026-06-24 13:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldTransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'واریز (افزایش موجودی طلا)'), ('WITHDRAWAL', 'برداشت (کاهش موجودی طلا)')], max_length=10, verbose_name='نوع تراکنش')),
                ('gold_weight', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='وزن طلا (گرم)')),
                ('gold_price_per_gram', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت هر گرم طلا (ریال)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان حذف')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gold_transactions', to='customers.customermodel', verbose_name='مشتری')),
                ('recorded_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transactions', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده (مدیر)')),
            ],
            options={
                'verbose_name': 'تراکنش طلا',
                'verbose_name_plural': 'تراکنش\u200cهای طلا',
                'ordering': ['-created_at'],
            },
        ),
    ]
