# Generated by Django 6.0.6 on 2026-06-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته\u200cبندی ویترین')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='اسلاگ (URL)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/products/', verbose_name='تصویر آیکون/دسته\u200cبندی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی محصول ویترین',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای محصولات ویترین',
            },
        ),
    ]
